### ISSUE TITLE
Add HTML comment instructions to help prevent merge conflicts

### ISSUE THREAD

**Issue by intelagense** [dailydotdev/memetoberfest#38]
We can add HTML comments to the README.md to clarify exactly where to add new code when editing.

Example: 
```html
Meme Image or link  | Twitter handle | Notes |
| --- | --- | --- |
| `<Meme image or link>` | `<Twitter handle>` | `<Notes>` | <!-- Use this format. Scroll down to the last row to add your meme. -->

<!-- Add your meme directly above this comment. -->

```
(Note: Table length will grow with each merge)

I am thinking this could help avoid merge conflicts and pull request revisions.

**Comment by FrancescoXX** [comment]
yes thanks for the idea @intelagense . do you want to make a pr on this? it will count as hacktoberfest contribution

**Comment by intelagense** [comment]
Yes. I will submit it shortly.
