### ISSUE TITLE
Memetoberfest should celebrate Hacktoberfest

### ISSUE THREAD

**Issue by codercatdev** [dailydotdev/memetoberfest#72]
I think you should add the label `hacktoberfest` to the repo 💜

<img width="372" alt="image" src="https://user-images.githubusercontent.com/3102249/195671172-0be010d9-6b2c-4abd-b346-c18798095940.png">

**Comment by max-programming** [comment]
@codercatdev I think they didn't add the `hacktoberfest` label for a reason. This way it will come under the `spam` category.

I know it is going to be organic and it's done by the right people. But I don't think it's a "project" or some repository where people learn something new by contributing 😄

**Comment by FrancescoXX** [comment]
what @max-programming said.
